export const IdmRoleConstants ={
    SYSTEM_ADMIN : "SYSTEM",

    DQ_ADMIN : "DQ_ADMIN",

	 JIM_ADMIN : "JIM_ADMIN",

	 DQ_USER : "DQ_USER",

	 JIM_BPA_ADMIN : "JIM_BPA_ADMIN",

	 JIM_BPA_USER : "JIM_BPA_USER",

	 JIM_VPP_ADMIN : "JIM_VPP_ADMIN",

	 JIM_VPP_USER : "JIM_VPP_USER",

	 JIM_ESD_ADMIN : "JIM_ESD_ADMIN",

	 JIM_ESD_USER : "JIM_ESD_USER",

	 JIM_EMGS_ADMIN : "JIM_EMGS_ADMIN",

	 JIM_EMGS_USER : "JIM_EMGS_USER",

	 VA_USER : "VA_USER",

	 OSC_USER : "OSC_USER",

	 OSC_ADMIN : "OSC_ADMIN",

	 RA_ADMIN : "RA_ADMIN",

	 RA_USER : "RA_USER",

	 USER_TYPE_BANK : "BANK",

	 BANK_PORTAL_ADMIN : "BANK_PORTAL_ADMIN",

	 BANK_HQ_ADMIN : "BANK_HQ_ADMIN",

	 BANK_HQ_USER : "BANK_HQ_USER",

	 BANK_BRANCH_ADMIN : "BANK_BRANCH_ADMIN",

	 BANK_BRANCH_USER : "BANK_BRANCH_USER",

	 BANK_SUPER_ADMIN : "BANK_SUPER_ADMIN",

	 ROLE_HC_BGD : "EMB_HC_BGD",

	 ROLE_HC_BGD_ADMIN : "EMB_HC_BGD_ADMIN",

	 ROLE_HC_ADMIN_BGD : "HC_ADMIN_BGD",

	 ROLE_HC_HC_BGD : "HC_HC_BGD",

	 ROLE_MOE : "URP_MOE",

	 ROLE_MOE_ADMIN : "URP_MOE_ADMIN",

	 GROUP_CODE_HC_BGD_ADMIN : "HC_ADMIN_BGD",

	 GROUP_CODE_HC_BGD : "HC_HC_BGD",
}