export const ERRORS_BN = {
    'password.errors.required': 'পাসওয়ার্ড প্রয়োজন।',
    'password.errors.minlength': 'সর্বনিম্ন 6 ডিজিট লিখুন।',
    'currPword.errors.required': 'বর্তমান পাসওয়ার্ড প্রয়োজন',
    'newPword.errors.required': 'নতুন পাসওয়ার্ড প্রয়োজন।',
    'repNewPword.errors.required': 'নতুন পাসওয়ার্ড নিশ্চিত করুন।',
    'fullname.errors.required': 'পুরো নাম প্রয়োজন',
    'firstName.errors.required': 'প্রথম নাম প্রয়োজন',
    'firstName.errors.valid': 'প্রথম নামটি অবৈধ',
    'nationalId.errors.required': 'জাতীয় আইডি / পাসপোর্ট প্রয়োজন',
    'email.errors.required': 'ইমেল প্রয়োজন',
    'email.errors.pattern': 'ইমেল ঠিকানা অবৈধ। (উদাঃ johndoe@company.com)',
    'phone.errors.required': 'মোবাইল নম্বর প্রয়োজন',
    'phone.errors.validatePhoneNumber': 'মোবাইল নম্বর অবৈধ',
    'dob.errors.required': 'জন্ম তারিখ প্রয়োজন',
    'userGroup.errors.required': 'ব্যবহারকারী গ্রুপ প্রয়োজনীয়  প্রয়োজন।',
    'userGroupBrnch.errors.required': 'শাখা প্রয়োজন',
    'userGroupCntry.errors.required': 'দেশ প্রয়োজন',
    'otp.errors.required': 'ওটিপি দরকার',
    'captcha.errors.required': 'কোড লিখুন',
    'captcha.errors.minlength': '',
    'level.errors.required': 'স্তরের বিবরণ প্রয়োজন',
    'roles.errors.required': 'ভূমিকা নির্ধারণ করা প্রয়োজন',
    'tranId.errors.required': 'লেনদেন আইডি প্রয়োজন',
    'typesDesc.errors.required': 'প্রকারের প্রয়োজন',
};
