export const ERRORS_EN = {
    'password.errors.required': 'Password is required.',
    'password.errors.minlength': 'Please enter minimum of 6 digit',
    'currPword.errors.required': 'Current Password is required',
    'newPword.errors.required': 'New Password is required',
    'repNewPword.errors.required': 'Confirm New Password is required',
    'fullname.errors.required': 'Fullname is required',
    'firstName.errors.required': 'Firstname is required',
    'firstName.errors.valid': 'Firstname is invalid',
    'nationalId.errors.required': 'National ID / Passport is required',
    'email.errors.required': 'Email is required',
    'email.errors.pattern': 'Email Address is invalid. (ex. johndoe@company.com)',
    'phone.errors.required': 'Mobile Number is required',
    'phone.errors.validatePhoneNumber': 'Mobile Number is invalid',
    'dob.errors.required': 'Date of Birth is required',
    'userGroup.errors.required': 'User Group is required',
    'userGroupBrnch.errors.required': 'Branch is required',
    'userGroupCntry.errors.required': 'Country is required',
    'otp.errors.required': 'OTP is required',
    'captcha.errors.required': 'Please enter code',
    'captcha.errors.minlength': '',
    'level.errors.required': 'Level Description is required',
    'roles.errors.required': 'Assign Roles is required',
    'tranId.errors.required': 'Transaction ID is required',
    'typesDesc.errors.required': 'Type is required',
    'userGroupRoleCode.errors.required': 'User Group Role Code is required.',
    'userRoleCode.errors.required': 'Role Code is required.',
    'menuCode.errors.required': 'Menu Code is required.',
    'menuDesc.errors.required': 'Menu Description is required.',
    'menuUrl.errors.required': 'Menu URL is required.',
    'menuIcon.errors.required': 'Menu Icon is required.',
    'clientId.errors.required': 'Client Id is required.',
    'portalTypeCode.errors.required': 'Portal Type Code is required.',
    'roleCode.errors.required': 'Role Code is required.',
    'roleDesc.errors.required': 'Role Description is required.',
    'userTypeCode.errors.required': 'User Type is required.',
    'branchCode.errors.required': 'Branch Code is required.',
    'branchName.errors.required': 'Branch Name is required.',
    'addr1.errors.required': 'Address 1 is required.',
    'addr2.errors.required': 'Address 2 is required.',
    'addr3.errors.required': 'Address 3 is required.',
    'addr4.errors.required': 'Address 4 is required.',
    'addr5.errors.required': 'Address 5 is required.',
    'cityCd.errors.required': 'City Code is required.',
    'stateCd.errors.required': 'State Code is required.',
    'cntryCd.errors.required': 'Country Code is required.',
    'zipcode.errors.required': 'Zip Code is required.',
    'contactNo.errors.required': 'Contact No is required.',
    'contactNo.errors.validatePhoneNumber': 'Phone Number validation failed.'
};
