export const ERRORS_MS = {
    'password.errors.required': 'Kata laluan diperlukan.',
    'password.errors.minlength': 'Sila masukkan minimum 6 digit',
    'currPword.errors.required': 'Kata laluan semasa diperlukan',
    'newPword.errors.required': 'Kata Laluan baru diperlukan.',
    'repNewPword.errors.required': 'Sahkan Kata Laluan Baru diperlukan.',
    'fullname.errors.required': 'Nama Penuh diperlukan.',
    'firstName.errors.required': 'Nama Pertama diperlukan.',
    'firstName.errors.valid': 'Nama Pertama tidak sah.',
    'nationalId.errors.required': 'Kad Pengenalan / Pasport diperlukan.',
    'email.errors.required': 'Emel tidak sah.',
    'email.errors.pattern': 'Alamat emel tidak sah. (ex. johndoe@company.com)',
    'phone.errors.required': 'Nombor mudah alih diperlukan.',
    'phone.errors.validatePhoneNumber': 'Nombor mudah alih tidak sah.',
    'dob.errors.required': 'Tarikh lahir diperlukan',
    'userGroup.errors.required': 'Kumpulan Pengguna diperlukan',
    'userGroupBrnch.errors.required': 'Cawangan diperlukan',
    'userGroupCntry.errors.required': 'Negara diperlukan',
    'otp.errors.required': 'OTP diperlukan',
    'captcha.errors.required': 'Sila masukkan kod',
    'captcha.errors.minlength': '',
    'level.errors.required': 'Keterangan Tahap diperlukan',
    'roles.errors.required': 'Peranan diperlukan',
    'tranId.errors.required': 'ID transaksi diperlukan',
    'typesDesc.errors.required': 'Jenis diperlukan',
    'userGroupRoleCode.errors.required': 'User Group Role Code is required.',
    'userRoleCode.errors.required': 'Role Code is required.',
    'menuCode.errors.required': 'Menu Code is required.',
    'menuDesc.errors.required': 'Menu Description is required.',
    'menuUrl.errors.required': 'Menu URL is required.',
    'menuIcon.errors.required': 'Menu Icon is required.',
    'clientId.errors.required': 'Client Id is required.',
    'portalTypeCode.errors.required': 'Portal Type Code is required.',
    'roleCode.errors.required': 'Role Code is required.',
    'roleDesc.errors.required': 'Role Description is required.',
    'userTypeCode.errors.required': 'User Type is required.',
    'branchCode.errors.required': 'Branch Code is required.',
    'branchName.errors.required': 'Branch Name is required.',
    'addr1.errors.required': 'Address 1 is required.',
    'addr2.errors.required': 'Address 2 is required.',
    'addr3.errors.required': 'Address 3 is required.',
    'addr4.errors.required': 'Address 4 is required.',
    'addr5.errors.required': 'Address 5 is required.',
    'cityCd.errors.required': 'City Code is required.',
    'stateCd.errors.required': 'State Code is required.',
    'cntryCd.errors.required': 'Country Code is required.',
    'zipcode.errors.required': 'Zip Code is required.',
    'contactNo.errors.required': 'Contact No is required.',
    'contactNo.errors.validatePhoneNumber': 'Phone Number validation failed.'
};
