export const ERRORS_BN = {
    'password.errors.required': 'পাসওয়ার্ড প্রয়োজন।',
    'password.errors.minlength': 'সর্বনিম্ন 6 ডিজিট লিখুন।',
    'currPword.errors.required': 'বর্তমান পাসওয়ার্ড প্রয়োজন',
    'newPword.errors.required': 'নতুন পাসওয়ার্ড প্রয়োজন।',
    'repNewPword.errors.required': 'নতুন পাসওয়ার্ড নিশ্চিত করুন।',
    'fullname.errors.required': 'পুরো নাম প্রয়োজন',
    'firstName.errors.required': 'প্রথম নাম প্রয়োজন',
    'firstName.errors.valid': 'প্রথম নামটি অবৈধ',
    'nationalId.errors.required': 'জাতীয় আইডি / পাসপোর্ট প্রয়োজন',
    'email.errors.required': 'ইমেল প্রয়োজন',
    'email.errors.pattern': 'ইমেল ঠিকানা অবৈধ। (উদাঃ johndoe@company.com)',
    'phone.errors.required': 'মোবাইল নম্বর প্রয়োজন',
    'phone.errors.validatePhoneNumber': 'মোবাইল নম্বর অবৈধ',
    'dob.errors.required': 'জন্ম তারিখ প্রয়োজন',
    'userGroup.errors.required': 'ব্যবহারকারী গ্রুপ প্রয়োজনীয়  প্রয়োজন।',
    'userGroupBrnch.errors.required': 'শাখা প্রয়োজন',
    'userGroupCntry.errors.required': 'দেশ প্রয়োজন',
    'otp.errors.required': 'ওটিপি দরকার',
    'captcha.errors.required': 'কোড লিখুন',
    'captcha.errors.minlength': '',
    'level.errors.required': 'স্তরের বিবরণ প্রয়োজন',
    'roles.errors.required': 'ভূমিকা নির্ধারণ করা প্রয়োজন',
    'tranId.errors.required': 'লেনদেন আইডি প্রয়োজন',
    'typesDesc.errors.required': 'প্রকারের প্রয়োজন',
    'userGroupRoleCode.errors.required': 'User Group Role Code is required.',
    'userRoleCode.errors.required': 'Role Code is required.',
    'menuCode.errors.required': 'Menu Code is required.',
    'menuDesc.errors.required': 'Menu Description is required.',
    'menuUrl.errors.required': 'Menu URL is required.',
    'menuIcon.errors.required': 'Menu Icon is required.',
    'clientId.errors.required': 'Client Id is required.',
    'portalTypeCode.errors.required': 'Portal Type Code is required.',
    'roleCode.errors.required': 'Role Code is required.',
    'roleDesc.errors.required': 'Role Description is required.',
    'userTypeCode.errors.required': 'User Type is required.',
    'branchCode.errors.required': 'Branch Code is required.',
    'branchName.errors.required': 'Branch Name is required.',
    'addr1.errors.required': 'Address 1 is required.',
    'addr2.errors.required': 'Address 2 is required.',
    'addr3.errors.required': 'Address 3 is required.',
    'addr4.errors.required': 'Address 4 is required.',
    'addr5.errors.required': 'Address 5 is required.',
    'cityCd.errors.required': 'City Code is required.',
    'stateCd.errors.required': 'State Code is required.',
    'cntryCd.errors.required': 'Country Code is required.',
    'zipcode.errors.required': 'Zip Code is required.',
    'contactNo.errors.required': 'Contact No is required.',
    'contactNo.errors.validatePhoneNumber': 'Phone Number validation failed.'
};
