export const ERRORS_EN = {
    'password.errors.required': 'Password is required.',
    'password.errors.minlength': 'Please enter minimum of 6 digit',
    'currPword.errors.required': 'Current Password is required',
    'newPword.errors.required': 'New Password is required',
    'repNewPword.errors.required': 'Confirm New Password is required',
    'fullname.errors.required': 'Fullname is required',
    'firstName.errors.required': 'Firstname is required',
    'firstName.errors.valid': 'Firstname is invalid',
    'nationalId.errors.required': 'National ID / Passport is required',
    'email.errors.required': 'Email is required',
    'email.errors.pattern': 'Email Address is invalid. (ex. johndoe@company.com)',
    'phone.errors.required': 'Mobile Number is required',
    'phone.errors.validatePhoneNumber': 'Mobile Number is invalid',
    'dob.errors.required': 'Date of Birth is required',
    'userGroup.errors.required': 'User Group is required',
    'userGroupBrnch.errors.required': 'Branch is required',
    'userGroupCntry.errors.required': 'Country is required',
    'otp.errors.required': 'OTP is required',
    'captcha.errors.required': 'Please enter code',
    'captcha.errors.minlength': '',
    'level.errors.required': 'Level Description is required',
    'roles.errors.required': 'Assign Roles is required',
    'tranId.errors.required': 'Transaction ID is required',
    'typesDesc.errors.required': 'Type is required',
};
