export const ERRORS_MS = {
    'password.errors.required': 'Kata laluan diperlukan.',
    'password.errors.minlength': 'Sila masukkan minimum 6 digit',
    'currPword.errors.required': 'Kata laluan semasa diperlukan',
    'newPword.errors.required': 'Kata Laluan baru diperlukan.',
    'repNewPword.errors.required': 'Sahkan Kata Laluan Baru diperlukan.',
    'fullname.errors.required': 'Nama Penuh diperlukan.',
    'firstName.errors.required': 'Nama Pertama diperlukan.',
    'firstName.errors.valid': 'Nama Pertama tidak sah.',
    'nationalId.errors.required': 'Kad Pengenalan / Pasport diperlukan.',
    'email.errors.required': 'Emel tidak sah.',
    'email.errors.pattern': 'Alamat emel tidak sah. (ex. johndoe@company.com)',
    'phone.errors.required': 'Nombor mudah alih diperlukan.',
    'phone.errors.validatePhoneNumber': 'Nombor mudah alih tidak sah.',
    'dob.errors.required': 'Tarikh lahir diperlukan',
    'userGroup.errors.required': 'Kumpulan Pengguna diperlukan',
    'userGroupBrnch.errors.required': 'Cawangan diperlukan',
    'userGroupCntry.errors.required': 'Negara diperlukan',
    'otp.errors.required': 'OTP diperlukan',
    'captcha.errors.required': 'Sila masukkan kod',
    'captcha.errors.minlength': '',
    'level.errors.required': 'Keterangan Tahap diperlukan',
    'roles.errors.required': 'Peranan diperlukan',
    'tranId.errors.required': 'ID transaksi diperlukan',
    'typesDesc.errors.required': 'Jenis diperlukan',
};
